// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ChczhXQdRtPAxBXLFCKZB7uK-4CQ6w4',
    appId: '1:467109773985:web:9d4273c60af41463d726e0',
    messagingSenderId: '467109773985',
    projectId: 'miaged-dc70a',
    authDomain: 'miaged-dc70a.firebaseapp.com',
    storageBucket: 'miaged-dc70a.appspot.com',
    measurementId: 'G-PDLR8MZD8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi6cdQ7vIEXKmN9T9TH-dMLdzjuG2nmtM',
    appId: '1:467109773985:android:514f9a1343668e24d726e0',
    messagingSenderId: '467109773985',
    projectId: 'miaged-dc70a',
    storageBucket: 'miaged-dc70a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWDbhkS2ZtFnDN3WJuQ8U12P2il2pQaA',
    appId: '1:467109773985:ios:f5f2efeb921c5671d726e0',
    messagingSenderId: '467109773985',
    projectId: 'miaged-dc70a',
    storageBucket: 'miaged-dc70a.appspot.com',
    iosBundleId: 'com.example.tpEmre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhWDbhkS2ZtFnDN3WJuQ8U12P2il2pQaA',
    appId: '1:467109773985:ios:f694e371d3c76c0ad726e0',
    messagingSenderId: '467109773985',
    projectId: 'miaged-dc70a',
    storageBucket: 'miaged-dc70a.appspot.com',
    iosBundleId: 'com.example.tpEmre.RunnerTests',
  );
}
